#!/bin/bash


PIDFILE=/var/run/pyWeather.pid
EXE=<PATHTO>/pyWeather.py
TSAPIKEY=<TSAPIKEY>


case $1 in
  start)
    start-stop-daemon --start --background --quiet --oknodo --pidfile $PIDFILE --exec $EXE --chdir `dirname $EXE` -- $TSAPIKEY
    sleep 2
    pgrep -f "$EXE" >$PIDFILE
    ;;
  stop)
	 start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    ;;
  status)
	status_of_proc -p $PIDFILE $EXE && exit 0 || exit $?
  ;;
esac

